@url = http://localhost:3001/api
@json = Content-Type: application/json

### 所有用户
get {{url}}/users

### 注册（请求头与参数之前一定要空一行）
post {{url}}/register
{{json}}

{
    "username":"user8",
    "password":"123456"
}
### 登录
post {{url}}/login
{{json}}

{
    "username":"user3",
    "password":"123456"
}

### 个人信息(客户端需要传token)
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNzg2ODQ4ODZhNzI5NTg2MDY2NzZjZCIsImlhdCI6MTU4NDk0OTM4MX0.h6D1r2IS14oUpSLtKgPVltNSZuMyI7KLwyM5ThHiycA